name: Notify Slack on merge

on:
  pull_request:
    types: [closed]

jobs:
  notify_slack_merge:
    name: Notify Slack on merge
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR Information
        id: extract_pr_info
        run: |
          PR_CREATOR=$(jq -r '.pull_request.user.login' $GITHUB_EVENT_PATH)
          PR_DESCRIPTION=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
          COMMIT_MESSAGES=$(git log --pretty=format:"%h - %an: %s" $GITHUB_SHA^..$GITHUB_SHA)
          echo "::set-output name=creator::$PR_CREATOR"
          echo "::set-output name=description::$PR_DESCRIPTION"
          echo "::set-output name=commits::$COMMIT_MESSAGES"

      - name: Send Notification to Slack
        uses: pullreminders/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{\"channel\":\"${{ secrets.SLACK_CHANNEL_ID }}\",\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request Created By:* ${{ steps.extract_pr_info.outputs.creator }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Pull Request Description:* ${{ steps.extract_pr_info.outputs.description }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"*Commit Messages:* ${{ steps.extract_pr_info.outputs.commits }}\"}}]}'
