name: Notify Slack on merge

on:
  pull_request:
    types: [closed]

jobs:
  notify_slack_merge:
    name: Notify Slack on merge
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR Information
        id: extract_pr_info
        run: |
          PR_AUTHOR=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
          PR_DESCRIPTION=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
          COMMIT_MESSAGE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
          echo "::set-output name=author::$PR_AUTHOR"
          echo "::set-output name=description::$PR_DESCRIPTION"
          echo "::set-output name=commit_message::$COMMIT_MESSAGE"

      - name: Send Notification to Slack
        uses: abinoda/slack-action@master
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          args: '{"channel":"${{ secrets.SLACK_CHANNEL_ID }}","blocks":[{"type":"section","text":{"type":"mrkdwn","text":"*Repository pushed to:* ${{ github.event.repository.name }}"}},{"type":"section","text":{"type":"mrkdwn","text":"*Pusher:* ${{ steps.extract_pr_info.outputs.author }}"}},{"type":"section","text":{"type":"mrkdwn","text":"*Commit Message:* ${{ steps.extract_pr_info.outputs.commit_message }}"}},{"type":"section","text":{"type":"mrkdwn","text":"*Description:* ${{ steps.extract_pr_info.outputs.description }}"}},{"type":"section","text":{"type":"mrkdwn","text":"<${{ github.event.repository.html_url }}|View Repository>"}}]}'
